defmodule AshRepro.Repo.Migrations.MigrateResources1 do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:users, primary_key: false) do
      add(:id, :bigserial, null: false, primary_key: true)
      add(:firstname, :text, null: false)
      add(:lastname, :text, null: false)
      add(:created_from_profile, :boolean, default: false)
      add(:inserted_at, :utc_datetime_usec, null: false, default: fragment("now()"))
      add(:updated_at, :utc_datetime_usec, null: false, default: fragment("now()"))
    end

    create table(:profiles, primary_key: false) do
      add(:id, :bigserial, null: false, primary_key: true)
      add(:contact_email, :text, null: false)
      add(:inserted_at, :utc_datetime_usec, null: false, default: fragment("now()"))
      add(:updated_at, :utc_datetime_usec, null: false, default: fragment("now()"))

      add(
        :user_id,
        references(:users,
          column: :id,
          name: "profiles_user_id_fkey",
          type: :bigint,
          prefix: "public"
        )
      )
    end
  end

  def down do
    drop(constraint(:profiles, "profiles_user_id_fkey"))

    drop(table(:profiles))

    drop(table(:users))
  end
end
